import './test/invalid-button-position.test';
import './test/invalid-button-size.test';
import './test/text-sizes-should-be-equal.test';
import './test/invalid-placeholder-size.test';
import './test/invalid-h2-position.test';
import './test/invalid-h3-position.test';
import './test/several-h1.test';
import './test/too-much-marketing-blocks.test';
import './test/validation.test';
